// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sakura.Persistence;

namespace Sakura.Persistence.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190106062955_AddPostViewId")]
    partial class AddPostViewId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Sakura.Persistence.PostResource", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("post_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message");

                    b.Property<long>("ViewId")
                        .HasColumnName("view_id");

                    b.HasKey("PostId")
                        .HasName("pk_posts");

                    b.HasIndex("ViewId")
                        .IsUnique()
                        .HasName("ix_posts_view_id");

                    b.ToTable("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
